name: Unzip and Summarize Zip Contents

on:
  workflow_dispatch:

jobs:
  unzip-and-combine:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allows pushing changes with GITHUB_TOKEN
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse config and unzip archives
        run: |
          # Create a temp directory for extraction
          mkdir -p temp_unzip
          # Read each zip filename from config.yml
          grep -E '^\\s*-' config.yml | sed 's/^[[:space:]]*-\\s*//;s/"//g' | while IFS= read -r zipfile; do
            echo "Unzipping $zipfile ..."
            unzip "$zipfile" -d temp_unzip
          done

      - name: Combine file contents
        run: |
          # Create or clear data.txt
          echo > data.txt
          # For every file in temp_unzip, append its contents to data.txt
          find temp_unzip -type f | while IFS= read -r filepath; do
            # Use relative path for display
            relpath="${filepath#temp_unzip/}"
            echo "===== File: $relpath =====" >> data.txt
            cat "$filepath" >> data.txt
            echo >> data.txt
          done

      - name: Commit and push data.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data.txt
          git commit -m "Add unzipped data summary"
          git push origin HEAD:main
