name: Unzip and Summarize One Zip File

on:
  workflow_dispatch:

jobs:
  unzip_summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install unzip and python deps
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          pip install pyyaml

      - name: Unzip and summarize contents into one data.txt
        run: |
          mkdir -p temp_unzip

          python3 <<EOF
import yaml
from pathlib import Path
import subprocess
import shutil

# Load config
with open("config.yml") as f:
    config = yaml.safe_load(f)

zip_files = config.get("unzip", [])
if not zip_files:
    print("❌ No zip files listed in config.yml")
    exit(1)

for zip_file in zip_files:
    zip_path = Path(zip_file)
    if not zip_path.exists():
        print(f"❌ Zip file not found: {zip_path}")
        continue

    temp_dir = Path("temp_unzip") / zip_path.stem
    if temp_dir.exists():
        shutil.rmtree(temp_dir)
    temp_dir.mkdir(parents=True)

    print(f"Unzipping {zip_path} to {temp_dir}")
    subprocess.run(["unzip", "-qq", str(zip_path), "-d", str(temp_dir)], check=True)

    output_path = Path("data.txt")
    with open(output_path, "a", encoding="utf-8") as out:
        out.write(f"\n\n===== Contents of {zip_file} =====\n\n")
        for file_path in sorted(temp_dir.rglob("*")):
            if file_path.is_file():
                try:
                    content = file_path.read_text(encoding="utf-8")
                except Exception as e:
                    content = f"<Failed to read file: {e}>"
                out.write(f"({file_path.relative_to(temp_dir)})\n-\n{content}\n\n")
    print(f"✅ Appended contents of {zip_file} to {output_path}")

    shutil.rmtree(temp_dir)
EOF

      - name: Commit data.txt only if changed
        run: |
          git config user.name "Zip Summarizer Bot"
          git config user.email "bot@example.com"
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git add data.txt
            git commit -m "Add/update combined data.txt from unzipped zip(s)"
            git push
          fi
