name: Unzip and Summarize One Zip File

on:
  workflow_dispatch:

jobs:
  unzip_and_summarize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install unzip
      run: sudo apt-get install -y unzip

    - name: Load config file
      id: config
      run: |
        echo "unzips=$(yq eval '.unzip[]' config.yml | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> "$GITHUB_ENV"

    - name: Unzip files
      run: |
        for file in $(echo $unzips | jq -r '.[]'); do
          folder="${file%.zip}"
          mkdir -p "$folder"
          unzip -o "$file" -d "$folder"
        done

    - name: Generate data.txt
      run: |
        echo "" > data.txt
        for file in $(echo $unzips | jq -r '.[]'); do
          folder="${file%.zip}"
          find "$folder" -type f | while read filepath; do
            echo "===== File: $filepath =====" >> data.txt
            cat "$filepath" >> data.txt
            echo -e "\n" >> data.txt
          done
        done

    - name: Commit and push results
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add data.txt */ || true
        git diff --cached --quiet || git commit -m "Add data.txt and unzipped folders"
        git push
