name: Unzip and Summarize
on:
  workflow_dispatch:        # Manual trigger
jobs:
  extract_and_summarize:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Allow pushing changes back to the repo:contentReference[oaicite:8]{index=8}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read config.yml and unzip files
        shell: bash
        run: |
          # Read each zip file from config.yml
          mapfile -t files < <(grep -oP '(?<=- ")(.*?)(?=")' config.yml)
          folders=()
          for file in "${files[@]}"; do
            # Derive folder name by removing .zip
            folder=$(basename "$file" .zip)
            folders+=("$folder")
            mkdir -p "$folder"
            echo "Unzipping '$file' into folder '$folder/'"
            unzip -q "$file" -d "$folder"
          done

      - name: Create data.txt summary of extracted files
        shell: bash
        run: |
          echo "" > data.txt
          for folder in "${folders[@]}"; do
            # List each file path and its contents
            find "$folder" -type f | while read filepath; do
              echo "${filepath}:" >> data.txt
              cat "$filepath" >> data.txt
              echo "" >> data.txt
            done
          done
          echo "Summary written to data.txt."

      - name: Commit and push changes
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          # Only commit if there are changes (e.g. new files or updated data.txt)
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Add unzipped folders and update data.txt"
            git push
          else
            echo "No new changes to commit."
          fi
